name: pals

on:
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-pals
  cancel-in-progress: true

jobs:
  unit_tests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: |
          pytest tests -v
